services:
  mysql:
    image: mysql:latest
    container_name: atividade-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123@senac
      MYSQL_DATABASE: patrimoniumdb
    ports:
      - "5030:3306"
    volumes:
      - dados:/var/lib/mysql
volumes:
  dados: