-- MySQL Script generated by MySQL Workbench
-- Mon Jun 29 11:56:45 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema casaoliveiradb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `casaoliveiradb` DEFAULT CHARACTER SET utf8 ;
USE `casaoliveiradb` ;

-- -----------------------------------------------------
-- Table `casaoliveiradb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaoliveiradb`.`cliente` (
  `codigo_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(60) NOT NULL,
  `cpf_cliente` VARCHAR(11) NOT NULL,
  `telefone_cliente` VARCHAR(15) NOT NULL,
  `email_cliente` VARCHAR(60) NOT NULL,
  `cep_cliente` VARCHAR(8) NOT NULL,
  `endereco_cliente` VARCHAR(50) NOT NULL,
  `data_nascimento_cliente` DATE NOT NULL,
  `sexo` ENUM("Masculino", "Feminino", "Outros") NOT NULL,
  `genero` VARCHAR(30) NULL,
  `etnia_cliente` VARCHAR(30) NOT NULL,
  `nome_social_cliente` VARCHAR(60) NULL,
  `estado_civil_cliente` VARCHAR(30) NOT NULL,
  `data_cadastro_cliente` DATE NOT NULL DEFAULT  current_timestramp(),
  PRIMARY KEY (`codigo_cliente`),
  UNIQUE INDEX `cpf_cliente_UNIQUE` (`cpf_cliente` ASC) VISIBLE,
  UNIQUE INDEX `email_cliente_UNIQUE` (`email_cliente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaoliveiradb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaoliveiradb`.`produto` (
  `codigo_produto` INT NOT NULL AUTO_INCREMENT,
  `nome_produto` VARCHAR(30) NOT NULL,
  `categoria` VARCHAR(30) NOT NULL,
  `descricao_produto` TEXT NOT NULL,
  `fabricante` VARCHAR(30) NOT NULL,
  `marca` VARCHAR(30) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `fabricacao` VARCHAR(30) NOT NULL,
  `validade` VARCHAR(30) NOT NULL,
  `lote` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`codigo_produto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaoliveiradb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaoliveiradb`.`funcionario` (
  `codigo_funcionario` INT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(60) NOT NULL,
  `cpf_funcionario` VARCHAR(11) NOT NULL,
  `rg_funcionario` VARCHAR(11) NOT NULL,
  `certidao_nascimento_filho` VARCHAR(30) NULL,
  `certidao_reservista` VARCHAR(12) NULL,
  `certidao_casamento` VARCHAR(30) NULL,
  `titulo_eleitor` VARCHAR(11) NULL,
  `telefone_funcionario` VARCHAR(15) NULL,
  `email_funcionario` VARCHAR(60) NOT NULL,
  `cep_funcionario` VARCHAR(8) NOT NULL,
  `endereco_funcionario` VARCHAR(50) NOT NULL,
  `data_nascimento_funcionario` DATE NOT NULL,
  `sexo_funcionario` ENUM("Maculino", "Feminino", "Outros") NOT NULL,
  `etnia_funcionario` VARCHAR(30) NOT NULL,
  `nome_social_funcionario` VARCHAR(60) NULL,
  `estado_civil_funcionario` VARCHAR(30) NOT NULL,
  `data_admissao` DATE NOT NULL DEFAULT  current_timestramp(),
  `data_demissao` DATE NULL,
  `escolaridade` ENUM("Fundamental", "Médio", "Graduação", "Pós-Graduação") NOT NULL,
  `pis` VARCHAR(11) NOT NULL,
  `cateira_trabalho` VARCHAR(11) NOT NULL,
  `cargo` VARCHAR(30) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`codigo_funcionario`),
  UNIQUE INDEX `cpf_funcionario_UNIQUE` (`cpf_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `rg_funcionario_UNIQUE` (`rg_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `certidao_nascimento_filho_UNIQUE` (`certidao_nascimento_filho` ASC) VISIBLE,
  UNIQUE INDEX `certidao_casamento_UNIQUE` (`certidao_casamento` ASC) VISIBLE,
  UNIQUE INDEX `certidao_reservista_UNIQUE` (`certidao_reservista` ASC) VISIBLE,
  UNIQUE INDEX `titulo_eleitor_UNIQUE` (`titulo_eleitor` ASC) VISIBLE,
  UNIQUE INDEX `telefone_funcionario_UNIQUE` (`telefone_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `email_funcionario_UNIQUE` (`email_funcionario` ASC) VISIBLE,
  UNIQUE INDEX `pis_UNIQUE` (`pis` ASC) VISIBLE,
  UNIQUE INDEX `cateira_trabalho_UNIQUE` (`cateira_trabalho` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaoliveiradb`.`estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaoliveiradb`.`estoque` (
  `codigo_estoque` INT NOT NULL AUTO_INCREMENT,
  `codigo_produto` INT NOT NULL,
  `fabricacao` DATE NOT NULL,
  `validade` DATE NOT NULL,
  `lote` VARCHAR(30) NOT NULL,
  `data_entrada` DATE NOT NULL DEFAULT  current_timestramp(),
  `quantidade_entrada` INT NOT NULL DEFAULT 1,
  `quantidade_atual` INT NOT NULL,
  `setor` VARCHAR(30) NOT NULL,
  `codigo_produto` INT NOT NULL,
  PRIMARY KEY (`codigo_estoque`),
  INDEX `fk_estoque_produto_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_estoque_produto`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `casaoliveiradb`.`produto` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaoliveiradb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaoliveiradb`.`venda` (
  `codigo_venda` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL DEFAULT  current_timestramp(),
  `total` DECIMAL(7,2) NOT NULL,
  `codigo_cliente` INT NOT NULL,
  `codigo_funcionario` INT NOT NULL,
  PRIMARY KEY (`codigo_venda`),
  INDEX `fk_venda_cliente1_idx` (`codigo_cliente` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`codigo_funcionario` ASC) VISIBLE,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `casaoliveiradb`.`cliente` (`codigo_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`codigo_funcionario`)
    REFERENCES `casaoliveiradb`.`funcionario` (`codigo_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaoliveiradb`.`itens_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaoliveiradb`.`itens_venda` (
  `codigo_itens_venda` INT NOT NULL AUTO_INCREMENT,
  `codigo_venda` INT NOT NULL,
  `codigo_produto` INT NOT NULL,
  `desconto` DECIMAL(4,2) NOT NULL DEFAULT 0.0,
  `quantidade` INT NOT NULL DEFAULT 1,
  `subtotal` DECIMAL(7,2) NOT NULL,
  `venda_codigo_venda` INT NOT NULL,
  `codigo_produto` INT NOT NULL,
  PRIMARY KEY (`codigo_itens_venda`),
  INDEX `fk_itens_venda_venda1_idx` (`venda_codigo_venda` ASC) VISIBLE,
  INDEX `fk_itens_venda_produto1_idx` (`codigo_produto` ASC) VISIBLE,
  CONSTRAINT `fk_itens_venda_venda1`
    FOREIGN KEY (`venda_codigo_venda`)
    REFERENCES `casaoliveiradb`.`venda` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itens_venda_produto1`
    FOREIGN KEY (`codigo_produto`)
    REFERENCES `casaoliveiradb`.`produto` (`codigo_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `casaoliveiradb`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `casaoliveiradb`.`pagamento` (
  `codigo_pagamento` INT NOT NULL AUTO_INCREMENT,
  `codigo_venda` INT NOT NULL,
  `forma_pagamento` ENUM("Pix", "Debito", "Credito", "Dinheiro") NOT NULL,
  `informacao_cartao` VARCHAR(255) NULL,
  `total_pagamento` DECIMAL(7,2) NOT NULL,
  `valor_recebido` DECIMAL(5,2) NOT NULL,
  `troco` DECIMAL(4,2) NOT NULL,
  `numero_parcelas` INT NOT NULL DEFAULT 1,
  `valor_parcela` DECIMAL(7,2) NULL,
  `status_quantidade` ENUM("Pendente", "Aprovado", "Recusado") NULL DEFAULT '\"Pendente\"',
  `codigo_venda` INT NOT NULL,
  PRIMARY KEY (`codigo_pagamento`),
  INDEX `fk_pagamento_venda1_idx` (`codigo_venda` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_venda1`
    FOREIGN KEY (`codigo_venda`)
    REFERENCES `casaoliveiradb`.`venda` (`codigo_venda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
