-- MySQL Script generated by MySQL Workbench
-- Fri Jul  3 11:08:06 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema horizonteViagensDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema horizonteViagensDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horizonteViagensDB` DEFAULT CHARACTER SET utf8 ;
USE `horizonteViagensDB` ;

-- -----------------------------------------------------
-- Table `horizonteViagensDB`.`Passagens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horizonteViagensDB`.`Passagens` (
  `idPassagens` INT NOT NULL AUTO_INCREMENT,
  `tipoPassagem` ENUM("Avião", "Ônibus") NOT NULL,
  `dataEmbarque` DATE NOT NULL,
  `horaEmbarque` TIME NOT NULL,
  `dataRetorno` DATE NOT NULL,
  `horaRetorno` TIME NOT NULL,
  `localEmbarque` VARCHAR(67) NOT NULL,
  `origem` VARCHAR(67) NOT NULL,
  `destino` VARCHAR(67) NOT NULL,
  `Passagenscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPassagens`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horizonteViagensDB`.`Hotel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horizonteViagensDB`.`Hotel` (
  `idHotel` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(67) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `complemento` VARCHAR(60) NOT NULL,
  `avaliacao` DECIMAL(2,1) NOT NULL,
  PRIMARY KEY (`idHotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horizonteViagensDB`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horizonteViagensDB`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(67) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `numeroTelefone` VARCHAR(11) NOT NULL,
  `cep` VARCHAR(50) NOT NULL,
  `data_nimento` DATE NOT NULL,
  `sexo` ENUM("Mulino", "Feminino", "Outros") NOT NULL,
  `data_admissao` DATE NOT NULL DEFAULT current_timestamp,
  `data_demissao` DATE NULL,
  `pis` VARCHAR(11) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ) ,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ) ,
  UNIQUE INDEX `numeroTelefone_UNIQUE` (`numeroTelefone` ) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horizonteViagensDB`.`Pacote de Viagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horizonteViagensDB`.`Pacote de Viagem` (
  `idPacoteViagem` INT NOT NULL AUTO_INCREMENT,
  `idPassagens` INT NOT NULL,
  `idHotel` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  `tipoHospedagem` ENUM("Hotel", "Pousada", "Resort") NOT NULL,
  `alimentacao` ENUM("Café", "Meia Pensão", "Pensão Completa") NOT NULL,
  `trasladoParadas` VARCHAR(100) NOT NULL DEFAULT 'Sem paradas',
  `passeiosExcursoes` VARCHAR(100) NOT NULL DEFAULT 'Sem Passeios/Excursões',
  `ingressos` VARCHAR(100) NOT NULL DEFAULT 'Sem Ingressos',
  `seguroViagens` ENUM("Sem Seguro Viagem", "Nivel 1", "Nivel 2", "Nivel 3") NOT NULL DEFAULT 'Sem Seguro Viagem',
  PRIMARY KEY (`idPacoteViagem`),
  INDEX `fk_Pacote de Viagem_Passagens_idx` (`idPassagens` ) ,
  INDEX `fk_Pacote de Viagem_Hotel1_idx` (`idHotel` ) ,
  INDEX `fk_Pacote de Viagem_Funcionario1_idx` (`idFuncionario` ) ,
  CONSTRAINT `fk_Pacote de Viagem_Passagens`
    FOREIGN KEY (`idPassagens`)
    REFERENCES `horizonteViagensDB`.`Passagens` (`idPassagens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacote de Viagem_Hotel1`
    FOREIGN KEY (`idHotel`)
    REFERENCES `horizonteViagensDB`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pacote de Viagem_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `horizonteViagensDB`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horizonteViagensDB`.`Cadastro dos Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horizonteViagensDB`.`Cadastro dos Clientes` (
  `idCadastroClientes` INT NOT NULL AUTO_INCREMENT,
  `idFuncionario` INT NOT NULL,
  `primeiroNome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(30) NOT NULL,
  `dataNimento` DATE NOT NULL,
  `email` VARCHAR(67) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `numeroTelefone` VARCHAR(11) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `complemento` VARCHAR(67) NOT NULL,
  `sexo` ENUM("Mulino", "Feminino", "Outros") NOT NULL,
  `nacionalidade` ENUM("Nativo", "Estrangeiro") NOT NULL,
  PRIMARY KEY (`idCadastroClientes`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ) ,
  UNIQUE INDEX `numeroTelefone_UNIQUE` (`numeroTelefone` ) ,
  INDEX `fk_Cadastro dos Clientes_Funcionario1_idx` (`idFuncionario` ) ,
  CONSTRAINT `fk_Cadastro dos Clientes_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `horizonteViagensDB`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horizonteViagensDB`.`Pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horizonteViagensDB`.`Pagamento` (
  `idPagamento` INT NOT NULL AUTO_INCREMENT,
  `valorTotal` DECIMAL(7,2) NOT NULL,
  `tipoPagamento` ENUM("Pix", "Credito", "Debito") NOT NULL,
  `quantidadeParcelas` INT NOT NULL DEFAULT 1,
  `valorParcelas` DECIMAL(7,2) NULL,
  `dataPagamento` DATE NOT NULL,
  `horaPagamento` TIME NOT NULL,
  PRIMARY KEY (`idPagamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horizonteViagensDB`.`Reservas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horizonteViagensDB`.`Reservas` (
  `idReservas` INT NOT NULL AUTO_INCREMENT,
  `idCadastroClientes` INT NOT NULL,
  `idPagamento` INT NOT NULL,
  `idPacoteViagem` INT NOT NULL,
  `dataReserva` DATE NOT NULL,
  PRIMARY KEY (`idReservas`),
  INDEX `fk_Reservas_Cadastro dos Clientes1_idx` (`idCadastroClientes` ) ,
  INDEX `fk_Reservas_Pagamento1_idx` (`idPagamento` ) ,
  INDEX `fk_Reservas_Pacote de Viagem1_idx` (`idPacoteViagem` ) ,
  CONSTRAINT `fk_Reservas_Cadastro dos Clientes1`
    FOREIGN KEY (`idCadastroClientes`)
    REFERENCES `horizonteViagensDB`.`Cadastro dos Clientes` (`idCadastroClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_Pagamento1`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `horizonteViagensDB`.`Pagamento` (`idPagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reservas_Pacote de Viagem1`
    FOREIGN KEY (`idPacoteViagem`)
    REFERENCES `horizonteViagensDB`.`Pacote de Viagem` (`idPacoteViagem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
